metadata:
  name: "sample-service-1-team-a"  # Optional, generated if not provided
  namespace: gloo-system           # Defaulted in template if not provided
  labels:
    example: sample-app-route       # Only unique or necessary labels
spec:
  hostnames:                        # Optional, generated if not provided
    - team-a.glootest.com
  rules:
    - backendRefs:
        - group: gloo.solo.io
          kind: Upstream
          name: sample-service-1-team-a
    matches:
      - path:
          type: PathPrefix
          value: /
  routeOption:
    jwt:
      disable: true               # Configurable: set to true/false
