metadata:
  name: "sample-service-1-team-a"  # Optional, generated if not provided
  namespace: gloo-system           # Defaulted in template if not provided
  labels:
    example: sample-app-route       # Only unique or necessary labels
spec:
  hostnames:                        # Optional, generated if not provided
    - team-a.glootest.com
  rules:
    - backendRefName: sample-service-1-team-a  # Derived from name if not provided
      pathPrefix: /
  routeOption:
    jwt:
      disable: true               # Configurable: set to true/false