apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-service-1-team-a-route
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: gloo-system
    server: "https://kubernetes.default.svc"
  source:
    repoURL: 'https://github.com/ably77/gloo-httproute-generator'
    targetRevision: HEAD
    path: "."
    helm:
      values: |
        metadata:
          name: "sample-service-1-team-a"
          namespace: gloo-system
          labels:
            example: sample-service-1-team-a-route
            gateway: https
        spec:
          hostnames:
            - "team-a.glootest.com"
          parentRefs:
            - name: https
              namespace: gloo-system
          rules: 
          - backendRefName: sample-service-1-team-a
            pathPrefix: /
            routeOptionName: sample-service-1-team-a-route-policies
          routeOption:
            jwt:
              disable: true
            
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
