apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yahoo-finance-route-route
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: gloo-system
    server: "https://kubernetes.default.svc"
  source:
    repoURL: 'https://github.com/ably77/gloo-httproute-generator'
    targetRevision: HEAD
    path: "."
    helm:
      values: |
        metadata:
          name: "yahoo-finance-route"
          namespace: gloo-system
          labels:
            example: yahoo-finance-route-route
            gateway: https
        spec:
          hostnames:
            - "yahoo-finance.glootest.com"
          parentRefs:
            - name: https
              namespace: gloo-system
          rules: 
          - backendRefName: yahoo-finance
            pathPrefix: /
            routeOptionName: yahoo-finance-route-route-policies
          routeOption:
            jwt:
              disable: true
            hostRewrite: query1.finance.yahoo.com
            extauth:
              configRef:
                name: foo-extauth
                namespace: gloo-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
