{{- $baseName := randAlphaNum 4 | lower }}
{{- $generatedName := printf "gloo-%s" $baseName }}
{{- $name := .Values.metadata.name | default $generatedName }}
{{- $namespace := .Values.metadata.namespace | default "gloo-system" }}
{{- $hostnames := .Values.spec.hostnames | default (list (printf "%s.glootest.com" $name)) }}
{{- $prefixPath := index .Values.metadata.labels "prefixPath" | default $name }}
{{- $routeOptionName := printf "%s-route-policies" $name }}
{{- $jwtDisabled := .Values.spec.routeOption.jwt.disable | default false }}
{{- $hostRewrite := .Values.spec.routeOption.hostRewrite | default "" }}
{{- $extAuthExists := hasKey .Values.spec.routeOption "extauth" }}  # Explicitly checking if extauth exists
---
# HTTPRoute resource
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ $name }}-route
  namespace: {{ $namespace }}
  labels:
    example: {{ .Values.metadata.labels.example | default $name }}
    gateway: {{ .Values.metadata.labels.gateway | default "https" }}
spec:
  hostnames:
{{- range $hostnames }}
    - {{ . }}
{{- end }}
  parentRefs:
    - name: "https"
      namespace: "gloo-system"
  rules:
{{- range .Values.spec.rules }}
    - backendRefs:
        - group: gloo.solo.io
          kind: Upstream
          name: {{ .backendRefName | default $name }}
      matches:
        - path:
            type: PathPrefix
            value: {{ .pathPrefix | default "/" }}
      filters:
        - type: ExtensionRef
          extensionRef:
            group: gateway.solo.io
            kind: RouteOption
            name: {{ .routeOptionName | default $routeOptionName }}
{{- end }}
---
# RouteOption resource
apiVersion: gateway.solo.io/v1
kind: RouteOption
metadata:
  name: {{ $routeOptionName }}
  namespace: {{ $namespace }}
spec:
  options:
    jwt:
      disable: {{ $jwtDisabled }}
{{- if $hostRewrite }}
    hostRewrite: {{ $hostRewrite }}
{{- end }}
{{- if $extAuthExists }}  # Only include if extauth key is present in values.yaml
    {{- if .Values.spec.routeOption.extauth.configRef.name }}  # Check if configRef.name exists
    extauth:
      configRef:
        name: {{ .Values.spec.routeOption.extauth.configRef.name }}
        namespace: {{ .Values.spec.routeOption.extauth.configRef.namespace | default "gloo-system" }}
    {{- end }}
{{- end }}
