apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: yahoo-finance
  namespace: gloo-system
spec:
  static:
    hosts:
      - addr: query1.finance.yahoo.com
        port: 443
  sslConfig: {}
